### ISSUE TITLE
freeze_model1.pb and freeze_model.pb

### ISSUE THREAD

**Issue by bettermanc** [jaideep99/HumanActiviyRecognition#1]
Hi, I want to consult you what's the difference between the "freeze_model.pb" and "freeze_model1.pb" which are in the APP Android-assets and how to generate the "freeze_model1.pb"?

Because when I use the code "private static final String MODEL_FILE = "file:///android_asset/freeze_model1.pb"", the app can successfully run in my mobile phone, when I use the code "private static final String MODEL_FILE = "file:///android_asset/freeze_model.pb"" , the app will crash. I don't know why it occurs.

**Comment by jaideep99** [comment]
I think one of it is not working. Both are for same purpose.

**Comment by jaideep99** [comment]
Okay. BTW,on what are you working on

**Comment by bettermanc** [comment]
> Okay. BTW,on what are you working on

I'm a student, just interested in the human activity recognition and want to transplant the model to my mobilephone to practice.

So can you tell me how to generate the "freeze_model1.pb"? Thank you!

**Comment by jaideep99** [comment]
I've renamed the file after it is generated, the first one freezed model.pb is failed, so i re ran my code and renamed it as freezedmodel1. The code is working,but it takes lot of time.

**Comment by bettermanc** [comment]
> I've renamed the file after it is generated, the first one freezed model.pb is failed, so i re ran my code and renamed it as freezedmodel1. The code is working,but it takes lot of time.

Amazing! Not change any code and just renamed the file name, then the app would successfully ran. I will try it in my code.

**Comment by jaideep99** [comment]
Have you ran the code?

**Comment by bettermanc** [comment]
> Have you ran the code?

yes, the code is working. Just as you said"it takes lot of time".

"Waiting for process to come online..."
